### ISSUE TITLE
Download page Dashboard

### ISSUE THREAD

**Issue by CassieColby** [HighlanderRobotics/lovat-website#11]

**Comment by CassieColby** [comment]
For now I think we should not have the questions (unless you think it can be coded quickly).
My idea:
Not currently affiliated with a FRC team:
- Download (all download info)
-Analyze  (link to vid, might have to be last years vid for a couple days)

Analyst (non scouting lead) on your FRC team:
-Download
-Join your team (using the team code from your scouting lead, make sure they registered your team already etc)
-Analyze (link to vid, might have to be last years vid for a couple days)

Scouting Lead on your FRC team
-Download
-Register your team (blurb about how it only happens once)
-Share your team code and manage scouters (link to scouting lead vid, and little blurb about the features)
-Analyze

**Comment by MangoSwirl** [comment]
> For now I think we should not have the questions (unless you think it can be coded quickly). My idea: Not currently affiliated with a FRC team:
> 
> * Download (all download info)
>   -Analyze  (link to vid, might have to be last years vid for a couple days)
> 
> Analyst (non scouting lead) on your FRC team: -Download -Join your team (using the team code from your scouting lead, make sure they registered your team already etc) -Analyze (link to vid, might have to be last years vid for a couple days)
> 
> Scouting Lead on your FRC team -Download -Register your team (blurb about how it only happens once) -Share your team code and manage scouters (link to scouting lead vid, and little blurb about the features) -Analyze

I agree. The [current layout](https://lovat.app/download) has a blurb on the left that we would need to update.
